#!/usr/bin/env bash
#display 4 bad luck, 8 is your chance

i=1

while [ "$i" -lt 11 ]; do

#using the if statement
    if [ "$i" -eq  4 ]; then
    echo "bad luck"
    elif [ "$i" -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi

    ((i++))
done
